#!/usr/bin/env bash

# bash completion for Flutter Version Manager (FVM)

if ! command -v fvm &> /dev/null; then
  return
fi

__fvm_generate_completion() {
  declare current_word
  current_word="${COMP_WORDS[COMP_CWORD]}"
  # shellcheck disable=SC2207
  COMPREPLY=($(compgen -W "$1" -- "${current_word}"))
  return 0
}

__fvm_commands() {
  declare current_word
  declare command

  current_word="${COMP_WORDS[COMP_CWORD]}"

  COMMANDS='
    help install uninstall use
    current list ls list-remote ls-remote
    cache deactivate unload
    version version-remote which'

  if [ ${#COMP_WORDS[@]} == 4 ]; then

    command="${COMP_WORDS[COMP_CWORD - 2]}"
    case "${command}" in
      alias) __fvm_installed_flutters ;;
    esac

  else

    case "${current_word}" in
      -*) __fvm_options ;;
      *) __fvm_generate_completion "${COMMANDS}" ;;
    esac

  fi
}

__fvm_options() {
  OPTIONS=''
  __fvm_generate_completion "${OPTIONS}"
}

__fvm_installed_flutters() {
  __fvm_generate_completion "$(fvm_ls)"
}

__fvm() {
  declare previous_word
  previous_word="${COMP_WORDS[COMP_CWORD - 1]}"

  case "${previous_word}" in
    use| ls | list | uninstall) __fvm_installed_flutters ;;
    *) __fvm_commands ;;
  esac

  return 0
}

# complete is a bash builtin, but recent versions of ZSH come with a function
# called bashcompinit that will create a complete in ZSH. If the user is in
# ZSH, load and run bashcompinit before calling the complete function.
if [[ -n ${ZSH_VERSION-} ]]; then
  # First calling compinit (only if not called yet!)
  # and then bashcompinit as mentioned by zsh man page.
  if ! command -v compinit > /dev/null; then
    autoload -U +X compinit && if [[ ${ZSH_DISABLE_COMPFIX-} = true ]]; then
      compinit -u
    else
      compinit
    fi
  fi
  autoload -U +X bashcompinit && bashcompinit
fi

complete -o default -F __fvm fvm