#!/usr/bin/env bash

DIR="$(command cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shellcheck disable=SC1090,SC1091
\. "$DIR/fvm.sh" --no-use

if [ -n "$FLUTTER_VERSION" ]; then
  fvm use "$FLUTTER_VERSION" > /dev/null || exit 127
elif ! fvm use >/dev/null 2>&1; then
  echo "No FLUTTER_VERSION provided; no .fvmrc file found" >&2
  exit 127
fi

exec "$@"